/**
 * 푸시 알림 전송 사유
 * @author 현웅
 */
export enum AlarmType {
  WIN_EXTRA_CREDIT = "WIN_EXTRA_CREDIT",
  NEW_COMMENT_TO_RESEARCH = "NEW_COMMENT_TO_RESEARCH",
  NEW_REPLY_TO_RESEARCH = "NEW_REPLY_TO_RESEARCH",
  NEW_COMMENT_TO_VOTE = "NEW_COMMENT_TO_VOTE",
  NEW_REPLY_TO_VOTE = "NEW_REPLY_TO_VOTE",
}
